# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-25 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='univeruser',
            name='univer_id2',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
