# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-25 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerapi', '0002_univeruser_univer_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='univeruser',
            name='univer_id2',
        ),
        migrations.AddField(
            model_name='univeruser',
            name='edx_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='univeruser',
            name='edx_pass',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='univeruser',
            name='univer_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
