# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-06 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerapi', '0003_auto_20211125_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='univeruser',
            name='edx_username',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
