# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-27 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Not Specified', max_length=255, verbose_name='Course Name')),
                ('university', models.CharField(blank=True, max_length=255, null=True, verbose_name='University')),
                ('content_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Content Type')),
                ('course_type', models.CharField(choices=[('MOOC', 'MOOC'), ('SPOC', 'SPOC'), ('none', 'None')], default='MOOC', max_length=50, verbose_name='Course Type (MOOC/SPOC)')),
                ('difficulty_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('none', 'None')], default='basic', max_length=50, verbose_name='Difficulty Level')),
                ('platform', models.CharField(default='Not Specified', max_length=255, verbose_name='Platform')),
                ('course_link', models.URLField(verbose_name='Course Link')),
                ('organization', models.CharField(default='Not Specified', max_length=255, verbose_name='Organization / University Offering the Course')),
                ('workload_hours', models.FloatField(default=0.0, verbose_name='Course Workload in Hours')),
                ('workload_credits', models.FloatField(default=0.0, verbose_name='Course Workload in Credits')),
                ('education_field', models.CharField(default='Not Specified', max_length=255, verbose_name='Field of Education')),
                ('training_direction', models.CharField(default='Not Specified', max_length=255, verbose_name='Training Direction')),
                ('op_code_name', models.TextField(default='Not Specified', verbose_name='Code and Name of the Program')),
                ('course_description', models.TextField(default='Description not provided', verbose_name='Course Description')),
                ('skills_covered', models.TextField(default='Skills not specified', verbose_name='Skills Covered')),
                ('course_language', models.CharField(default='Russian', max_length=100, verbose_name='Course Language')),
                ('related_disciplines', models.CharField(default='Not Specified', max_length=255, verbose_name='Discipline(s) for Credit Transfer')),
                ('credit_workload', models.FloatField(default=0.0, verbose_name='Credit Workload')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
