# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-28 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake_catalog', '0003_retakecatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retakecatalog',
            name='difficulty_level',
            field=models.CharField(choices=[('\u0431\u0430\u0437\u043e\u0432\u044b\u0439', '\u0431\u0430\u0437\u043e\u0432\u044b\u0439'), ('\u0441\u0440\u0435\u0434\u043d\u0438\u0439', '\u0441\u0440\u0435\u0434\u043d\u0438\u0439'), ('\u043f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439', '\u043f\u0440\u043e\u0434\u0432\u0438\u043d\u0443\u0442\u044b\u0439'), ('none', 'None')], default='basic', max_length=50, verbose_name='Difficulty Level'),
        ),
    ]
