# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-28 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retake_catalog', '0004_auto_20241127_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retakecatalog',
            name='created',
        ),
    ]
