# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-28 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake_catalog', '0005_remove_retakecatalog_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retakecatalog',
            name='course_type',
            field=models.CharField(choices=[('MOOC', 'MOOC'), ('SPOC', 'SPOC'), ('Coursera', 'Coursera'), ('none', 'None')], default='MOOC', max_length=50, verbose_name='Course Type (MOOC/SPOC)'),
        ),
    ]
